[project]
name = "study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.1",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pre-commit>=4.5.1",
    "ruff>=0.15.0",
]
test = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]

# Pytest config
[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["app", "lambdas"]
pythonpath = ["."]

addopts = [
    "-ra",
    "--strict-config",
    "--strict-markers",
    "--disable-warnings",
]

python_files = ["*_test.py","tests.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# Ruff config
[tool.ruff]
line-length = 100
target-version = "py313"
exclude = [
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
    "infra"
]
[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B",
    "SIM",
]
ignore = [
    "E501",
]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true

[tool.ruff.lint.per-file-ignores]
"app/**/tests/**" = ["S101"]
"lambdas/**/tests/**" = ["S101"]
